// Warrior roster — stats, colors, and metadata for all 10 fighters
// Speed/Power/Health are multipliers on base values (1.0 = default)

export const WARRIORS = [
  {
    id: 'knight',
    name: 'Medieval Knight',
    era: 'Europe, ~1200s',
    weapon: 'Longsword',
    speed: 0.85,
    power: 1.0,
    health: 1.2,
    colors: {
      primary: '#4a6fa5',
      secondary: '#c0c0c0',
      accent: '#ffd700',
      skin: '#f5d6b8',
    },
    special: {
      name: 'Mordhau',
      description: 'Devastating pommel-strike reversal',
      damage: 30,
      meterCost: 100,
    },
    ai: {
      aggression: 0.3,
      defense: 0.8,
      counterTendency: 0.7,
      specialThreshold: 0.4,
      patternVariation: 0.4,
    },
    arena: 'castle',
  },
  {
    id: 'samurai',
    name: 'Samurai',
    era: 'Japan, ~1600s',
    weapon: 'Katana',
    speed: 1.1,
    power: 1.0,
    health: 1.0,
    colors: {
      primary: '#8b0000',
      secondary: '#2d2d2d',
      accent: '#ff4444',
      skin: '#f0d5a8',
    },
    special: {
      name: 'Iaijutsu',
      description: 'Lightning-fast draw-cut',
      damage: 28,
      meterCost: 100,
    },
    ai: {
      aggression: 0.4,
      defense: 0.6,
      counterTendency: 0.9,
      specialThreshold: 0.5,
      patternVariation: 0.5,
    },
    arena: 'dojo',
  },
  {
    id: 'viking',
    name: 'Viking',
    era: 'Scandinavia, ~900s',
    weapon: 'Sword & Axe',
    speed: 0.95,
    power: 1.2,
    health: 1.0,
    colors: {
      primary: '#5c4033',
      secondary: '#8b7355',
      accent: '#4fc3f7',
      skin: '#f5d6b8',
    },
    special: {
      name: 'Berserker Rush',
      description: 'Rapid multi-hit charge',
      damage: 32,
      meterCost: 100,
    },
    ai: {
      aggression: 0.9,
      defense: 0.2,
      counterTendency: 0.3,
      specialThreshold: 0.8,
      patternVariation: 0.6,
    },
    arena: 'longship',
  },
  {
    id: 'gladiator',
    name: 'Roman Gladiator',
    era: 'Rome, ~100 AD',
    weapon: 'Gladius & Shield',
    speed: 1.0,
    power: 1.0,
    health: 1.05,
    colors: {
      primary: '#b8860b',
      secondary: '#8b4513',
      accent: '#ff6347',
      skin: '#d4a574',
    },
    special: {
      name: 'Shield Bash Combo',
      description: 'Stun + follow-up strikes',
      damage: 26,
      meterCost: 100,
    },
    ai: {
      aggression: 0.5,
      defense: 0.6,
      counterTendency: 0.5,
      specialThreshold: 0.5,
      patternVariation: 0.7,
    },
    arena: 'colosseum',
  },
  {
    id: 'mongol',
    name: 'Mongol',
    era: 'Central Asia, ~1200s',
    weapon: 'Curved Sword',
    speed: 1.15,
    power: 0.9,
    health: 0.85,
    colors: {
      primary: '#6b8e23',
      secondary: '#deb887',
      accent: '#ff8c00',
      skin: '#d4a574',
    },
    special: {
      name: 'Feigned Retreat',
      description: 'Dodge back + devastating counter',
      damage: 25,
      meterCost: 100,
    },
    ai: {
      aggression: 0.6,
      defense: 0.4,
      counterTendency: 0.8,
      specialThreshold: 0.6,
      patternVariation: 0.8,
    },
    arena: 'steppe',
  },
  {
    id: 'spartan',
    name: 'Spartan',
    era: 'Greece, ~480 BC',
    weapon: 'Short Sword & Shield',
    speed: 0.85,
    power: 1.05,
    health: 1.15,
    colors: {
      primary: '#8b0000',
      secondary: '#b8860b',
      accent: '#ffd700',
      skin: '#d4a574',
    },
    special: {
      name: 'Phalanx Strike',
      description: 'Unblockable shield-charge thrust',
      damage: 28,
      meterCost: 100,
    },
    ai: {
      aggression: 0.3,
      defense: 0.9,
      counterTendency: 0.6,
      specialThreshold: 0.3,
      patternVariation: 0.3,
    },
    arena: 'thermopylae',
  },
  {
    id: 'pirate',
    name: 'Pirate',
    era: 'Caribbean, ~1700s',
    weapon: 'Cutlass',
    speed: 1.05,
    power: 0.95,
    health: 0.95,
    colors: {
      primary: '#2f1b14',
      secondary: '#8b0000',
      accent: '#ffd700',
      skin: '#d4a574',
    },
    special: {
      name: 'Powder Flash',
      description: 'Blind + slash combo',
      damage: 24,
      meterCost: 100,
    },
    ai: {
      aggression: 0.6,
      defense: 0.3,
      counterTendency: 0.4,
      specialThreshold: 0.7,
      patternVariation: 0.9,
    },
    arena: 'dock',
  },
  {
    id: 'zulu',
    name: 'Zulu Warrior',
    era: 'Southern Africa, ~1800s',
    weapon: 'Iklwa (Short Spear)',
    speed: 1.1,
    power: 1.05,
    health: 0.9,
    colors: {
      primary: '#8b4513',
      secondary: '#f5f5dc',
      accent: '#ff4500',
      skin: '#6b3a2a',
    },
    special: {
      name: 'Bull Horn',
      description: 'Rapid encircling multi-strike',
      damage: 30,
      meterCost: 100,
    },
    ai: {
      aggression: 0.8,
      defense: 0.3,
      counterTendency: 0.5,
      specialThreshold: 0.7,
      patternVariation: 0.5,
    },
    arena: 'savanna',
  },
  {
    id: 'conquistador',
    name: 'Conquistador',
    era: 'Spain, ~1500s',
    weapon: 'Toledo Rapier',
    speed: 1.0,
    power: 1.0,
    health: 1.0,
    colors: {
      primary: '#191970',
      secondary: '#c0c0c0',
      accent: '#ffd700',
      skin: '#f0d5a8',
    },
    special: {
      name: 'Estocada',
      description: 'Precision thrust, high damage',
      damage: 32,
      meterCost: 100,
    },
    ai: {
      aggression: 0.4,
      defense: 0.5,
      counterTendency: 0.7,
      specialThreshold: 0.4,
      patternVariation: 0.4,
    },
    arena: 'temple',
  },
  {
    id: 'seal',
    name: 'Navy SEAL',
    era: 'Modern',
    weapon: 'Rifle (as sword)',
    speed: 1.1,
    power: 1.1,
    health: 0.9,
    colors: {
      primary: '#2d4a2d',
      secondary: '#1a1a1a',
      accent: '#ff0000',
      skin: '#d4a574',
    },
    special: {
      name: 'Buttstroke Barrage',
      description: 'Rifle CQC combo',
      damage: 30,
      meterCost: 100,
    },
    ai: {
      aggression: 0.7,
      defense: 0.5,
      counterTendency: 0.8,
      specialThreshold: 0.5,
      patternVariation: 0.6,
    },
    arena: 'carrier',
  },
];

export function getWarriorById(id) {
  return WARRIORS.find(w => w.id === id);
}
